### ISSUE TITLE
DateFormat : DateTime not working with bonita 7.2

### ISSUE THREAD

**Issue by KilianStein** [Bonitasoft-Community/restapi_context#8] opened 2017-03-31 04:45 UTC
In our bonita 7.2, i find that this pattern ""yyyy-MM-dd'T'HH:mm:ssZ"" not working with contract bonita 

Erreurs détectées :
2016-04-20T11:00:00+1100 cannot be assigned to DATE

I suggest to use "yyyy-MM-dd'T'HH:mm:ss" or "yyyy-MM-dd'T'HH:mm:ss'Z'" (as angular do) as dateTimeFormat or to create a dateBonitaContractFormat

exemple :
private static SimpleDateFormat sdfDateTime = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
or 
private static SimpleDateFormat sdfDateBonitaTime = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");

Do you have the same issue with lastest bonita version ?

**Comment by pierre-yves-monnet** [comment] 2017-03-31 17:51
I have to check. I understand that you get this information from the REST API and return it a contract. Do you use a DatePicker or not (I mean, do you directly return the value to the contract ? )

DatePicker should to translate the value.

In my process, I get the value on the contract as a STRING (look in the community the Date Time information), because I work in the USA in a different time zone than Greenwich.

**Comment by KilianStein** [comment] 2017-04-02 22:31
Hello Pierre-Yves,

I use  DatePicker. But DatePicker don't udapte the data if you dont interact with it.

My problem is this case  : DateFromContextAcess -directly go to -> Bonita Contract Date.

This is my believe : In version 7.2 bonita, Dates are store in UTC values (maybe i'm wrong). So we manipulate UTC date in the engine and we show dates in UI in the current datetime (here PacificTime, i work in New Caledonia :p ). I suppose that bonitadate from contract is waiting for a utc date without any timezone...

**Comment by nurlix** [comment] 2017-07-17 05:33
Hi.
i don't want to create a new issue. its more like a question.
So is it possible to make work uiDate for bpm dates like` start, end_date, last_update_date` etc
For example : 

`{{$item.start|uiDate : 'short'}}`
`{{$item.start|uiDate : 'dd-mm-yyy'}}` //any combination

 still gives something like 2017-07-14 18:38:48.136

although BDM dates are fine
 
tnx

**Comment by pierre-yves-monnet** [comment] 2017-07-17 16:13
hello,
You have to use the "format" operation to calculate the correct format. if you use the Standard widget, you have to know if you have a Date Time widget, a "meeting" widget or an "open hour" widget. look in the PDF, there are a chapter on date. Tell me if it is comprehensible.

**Comment by nurlix** [comment] 2017-07-18 05:51
Hi
 sorry i didnt get it.  You mean something like that

**Comment by nurlix** [comment] 2017-07-19 05:36
Hi.
I'm sorry i didnt get it.
normaly i would do something like this
`$scope.adate=new Date( somedatestring );`
or
`$scope.adate=new Date( somedatestring ).format('MM/dd/yyyy');`
`{{ adate| date:'MM/dd/yyyy'}}` which would work fine
but it involves javascript which i dont want
so how and where do i do it in UI designer
tnx

**Comment by pierre-yves-monnet** [comment] 2017-07-19 17:41
You should not need any javascript.
1/ which Bonita version do you use ? 7.5 or not (in 7.5, new widget date appears)
2/ which widget do you use for the date ? Bonita Date widget ? Community Date Widget ? Text widget (because you speak about {{ adate| date:'MM/dd/yyyy'}} : you don't use this form in a Date widget)
3/ what is exactly your issue ? Is that you have a date in your BDM and you want to display it in a Date widget ? And ? You don't have the same date than in the BDM ? 
Check the date you have in the BDM, because the issue is may not when you READ the date from the BDM, but when you WRITE the date to your BDM. Have a look on the Date Community Widget to understand this use case.

**Comment by nurlix** [comment] 2017-07-20 05:57
Hi.
i'm sorry. i forgot that i'm in restapi_context branch. its actually bonita engine issue.
So never mind.
tnx

**Comment by pierre-yves-monnet** [comment] 2019-03-19 17:51
So, let's close this issue ...

**Closed as completed** 2019-03-19 17:51 UTC
